### ISSUE TITLE
Change prompt-sync library for prompt-sync-plus

### ISSUE THREAD

**Issue by heliomar-pena** [heliomar-pena/i18n-populator#41]
I found some bugs on the prompt-sync library and then noticed that the library was not longer maintained over 2019 and PRs than fix the bugs that we have already existed for at least one year but were not merged yet.

Looking for an alternative, I found this library https://github.com/Vpet95/prompt-sync-plus. It is a clone of prompt-sync but with some bugs fixed so as code improvements

The purpose of this issue is to try to migrate to prompt-sync-plus, as the doc mention it should be only install and require, but we don't need to perform changes on our old code of prompt-sync, so should be easy to made.

After of implementing it, we need tests if all works properly and if there is not bugs with the old code.

**Comment by victor-heliomar** [comment]
Please notice here is needed to update the project for support the [javascript's modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) before install it
